# Generated by Django 3.0.3 on 2020-02-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diligencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diligencia',
            options={'verbose_name': 'Diligência', 'verbose_name_plural': 'Diligências'},
        ),
    ]
